services:
  - type: web
    name: order-execution
    env: node
    buildCommand: npm run build
    startCommand: export NODE_ENV=production && npm run migrate && npm start
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: order-execution-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: order-execution-db
          property: connectionString

  - type: redis
    name: order-execution-redis
    ipAllowList: []
    plan: free

databases:
  - name: order-execution-db
    databaseName: order_execution
    user: orders_user
    plan: free
