services:
  - type: web
    name: order-execution
    env: node
    buildCommand: npm run build
    startCommand: export NODE_ENV=production && npm run migrate && npm start
    envVars:
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: order-execution-db
          property: connectionString

databases:
  - name: order-execution-db
    databaseName: order_execution
    user: orders_user
    plan: free
